export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SESSION_ERROR = 'SESSION_ERROR';

export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_OAUTH = 'USER_OAUTH';
export const LOGOUT = 'LOGOUT';

export const SHOW_ALERTS = 'SHOW_ALERTS';  
export const REMOVE_ALERTS = 'REMOVE_ALERTS';

export const NEW_BOOK = 'NEW_BOOK';
export const NEW_BOOK_SUCCESS = 'NEW_BOOK_SUCCESS';
export const NEW_BOOK_ERROR = 'NEW_BOOK_ERROR';

export const UPDATE_BOOK = 'UPDATE_BOOK';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';

export const SET_DELETE_BOOK_MODAL = 'SET_DELETE_BOOK_MODAL';

export const SET_BOOKS_SEARCHED = 'SET_BOOKS_SEARCHED';

export const NEW_USER = 'NEW_USER';
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_ERROR = 'NEW_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const NEW_BORROWED_BOOK = 'NEW_BORROWED_BOOK';
export const NEW_BORROWED_BOOK_SUCCESS = 'NEW_BORROWED_BOOK_SUCCESS';
export const NEW_BORROWED_BOOK_ERROR = 'NEW_BORROWED_BOOK_ERROR';

export const RETURN_BORROWED_BOOK = 'NEW_BORROWED_BOOK';
export const RETURN_BORROWED_BOOK_SUCCESS = 'RETURN_BORROWED_BOOK_SUCCESS';
export const RETURN_BORROWED_BOOK_ERROR = 'RETURN_BORROWED_BOOK_ERROR';

export const RESET_STATE = 'RESET_STATE';

export const SET_BOOK = 'SET_BOOK';
